### ISSUE TITLE
Test view

### ISSUE THREAD

**Issue by lpsandaruwan** [fontman/fontman-desktop#8]
Implement Font tests view

**Comment by lpsandaruwan** [comment]
![test_view](https://cloud.githubusercontent.com/assets/5220773/22199945/fe4c50ae-e182-11e6-944d-af6c4ea33027.png)

**Comment by pathumego** [comment]
Remove the close button on the bottom :) top close is enough

**Comment by lpsandaruwan** [comment]
Done.

![test_view](https://cloud.githubusercontent.com/assets/5220773/22200984/a76c34ca-e187-11e6-8a84-003c4dbf3011.png)
